# The URL the site will be built for
base_url = "https://thainguyen.space"

title = "Nguyen's rambling corner"
description = "My personal blog!"
theme = "anemone"
default_language = "en"
compile_sass = true
minify_html = true
generate_feed = true

taxonomies = [{ name = "tags" }]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "dracula"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Nguyen Thai"
display_author = true
favicon = "favicon.ico"
image = ""
default_theme = "dark"
list_pages = false
twitter_card = true
header_nav = [
    { name_en = "/home/", url = "/" },
    { name_en = "/about/", url = "/about" },
    { name_en = "/posts/", url = "/posts" },
]

comment_url = "https://comments.thainguyen.space"
comment_site_id = "b2d3751e-6b89-42aa-a2c5-4df2e755d4f8"
