# The URL the site will be built for
base_url = "https://thainguyen.space"

title = "Nguyen's rambling corner"
description = "My personal blog!"
theme = "anemone"
default_language = "en"
compile_sass = true
minify_html = true
generate_feed = true

taxonomies = [{ name = "tags" }]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "dracula"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Nguyen Thai"
favicon = "favicon.ico"
image = ""
list_pages = false
twitter_card = true

header_nav = [
    { name = "/home/", url = "/" },
    { name = "/about/", url = "/about" },
    { name = "/posts/", url = "/posts" },
]
