# The URL the site will be built for
base_url = "https://thainguyen.space"

title = "Nguyen's rambling corner"
description = "My personal blog!"
theme = "anemone"
default_language = "en"
compile_sass = true
minify_html = true
generate_feeds = true

taxonomies = [{ name = "tags" }]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "dracula", filename = "css/dracula-theme.css" },
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Nguyen Thai"
display_author = true
favicon = "favicon.ico"
image = ""
default_theme = "dark"
list_pages = false
twitter_card = true
header_nav = [
    { name_en = "/home/", url = "/" },
    { name_en = "/posts/", url = "/posts" },
    { name_en = "/about/", url = "/about" },
]
